// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-DSd_bQE6pFCi58eSG-U06eDbxhRJuk',
    appId: '1:379015410044:web:d4b19edb028038fa9c74f9',
    messagingSenderId: '379015410044',
    projectId: 'yalapay-b6a03',
    authDomain: 'yalapay-b6a03.firebaseapp.com',
    storageBucket: 'yalapay-b6a03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaDNIOt4GmrQ4GMqoQEQ4JkOBApedDLYg',
    appId: '1:379015410044:android:f63f42f82ad27d519c74f9',
    messagingSenderId: '379015410044',
    projectId: 'yalapay-b6a03',
    storageBucket: 'yalapay-b6a03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZmqwOxcofCUS-UtkuSpu1bZSRSiUX4c',
    appId: '1:379015410044:ios:fe5c911682b715529c74f9',
    messagingSenderId: '379015410044',
    projectId: 'yalapay-b6a03',
    storageBucket: 'yalapay-b6a03.firebasestorage.app',
    iosBundleId: 'com.example.yalaPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZmqwOxcofCUS-UtkuSpu1bZSRSiUX4c',
    appId: '1:379015410044:ios:fe5c911682b715529c74f9',
    messagingSenderId: '379015410044',
    projectId: 'yalapay-b6a03',
    storageBucket: 'yalapay-b6a03.firebasestorage.app',
    iosBundleId: 'com.example.yalaPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW-DSd_bQE6pFCi58eSG-U06eDbxhRJuk',
    appId: '1:379015410044:web:c069d1852568c0619c74f9',
    messagingSenderId: '379015410044',
    projectId: 'yalapay-b6a03',
    authDomain: 'yalapay-b6a03.firebaseapp.com',
    storageBucket: 'yalapay-b6a03.firebasestorage.app',
  );
}
